/* ============================================================
   Clinical Guidelines module
   Authored by Sanjay Sivalokanathan. Ported from the Wix site.
   These are quick-reference pathways — verify doses against
   institutional protocols before acting.
   ============================================================ */
CARDS.register({
  id: 'guidelines',
  title: 'Clinical Guidelines',
  icon: '📑',
  items: [
    {
      id: 'acs', type: 'ref',
      title: "Acute Coronary Syndrome",
      subtitle: "STEMI / NSTEMI",
      keywords: "acs stemi nstemi chest pain troponin pci ticagrelor",
      body: `<h3 class="g-h">Suspect</h3><ul class="g-list"><li>Central/retrosternal pressure, tightness, heaviness; radiation to jaw or shoulder; nausea/vomiting; breathlessness.</li><li>Risk factors: HTN, DM, smoking, HLD, family history.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>EKG, VBG (electrolytes, pH, lactate).</li><li>Labs: troponin, CBC, NT-proBNP, CMP, lipids, coags, UDS.</li><li>Imaging: CXR (signs of HF), echocardiogram. Monitor on telemetry/CCU.</li></ul><h3 class="g-h">Diagnostic criteria</h3><ul class="g-list"><li><strong>STEMI:</strong> ST elevation ≥0.2 mm V1–V3 or ≥0.1 mm other leads; new LBBB.</li><li><strong>NSTEMI:</strong> symmetrical deep TWI ≥2 mm, transient ST elevation, Wellens (LAD), persistent ST depression ≥1 mm.</li><li>Risk-stratify with TIMI or GRACE.</li></ul><h3 class="g-h">Management</h3><ul class="g-list"><li><strong>Aspirin:</strong> 325 mg load, then 81 mg daily.</li><li><strong>P2Y12:</strong> ticagrelor 180 mg → 90 mg BID; or prasugrel 60 mg → 10 mg/day (5 mg in East Asian); or clopidogrel 600 mg → 75 mg/day. Confirm with interventional cardiology first.</li><li><strong>Anticoagulation:</strong> start UFH per protocol.</li><li><strong>Oxygen:</strong> target ≥94%.</li><li><strong>Nitrates:</strong> isosorbide dinitrate/mononitrate, NTG patch, or SL.</li><li><strong>Beta-blocker:</strong> avoid if brady <50, 2nd/3rd-degree block, acute HF, bronchospasm. Start low, titrate.</li><li><strong>Statin:</strong> atorvastatin 40 mg → 80 mg (interacts with verapamil, diltiazem, amiodarone).</li><li><strong>MRA:</strong> in STEMI and those with HF.</li><li><strong>PPI:</strong> omeprazole 20 mg daily to reduce GI bleed.</li><li><strong>Glucose:</strong> target <180 mg/dL.</li><li><strong>PCI:</strong> for STEMI, aim within 90 min of ED arrival.</li></ul><h3 class="g-h">Complications</h3><ul class="g-list"><li>Arrhythmia, heart failure, cardiogenic shock.</li><li>MINOCA: 9–14% have no culprit lesion (clot lysis, vasospasm, myocarditis, microvascular disease).</li></ul>`
    },
    {
      id: 'hf', type: 'ref',
      title: "Acute Heart Failure",
      subtitle: "HFrEF / HFpEF / HFmrEF",
      keywords: "heart failure hfref hfpef gdmt diuretic sglt2 mra arni",
      body: `<h3 class="g-h">Classify</h3><ul class="g-list"><li>NYHA I–IV. HFrEF ≤40%; HFmrEF 41–49%; HFpEF ≥50%.</li><li>Risk factors: HTN, diabetes, obesity, cardiotoxic agents, familial cardiomyopathy.</li><li>Precipitants: ACS, uncontrolled HTN, arrhythmia, infection, non-adherence, anemia, thyroid disease, Na-retaining/negative-inotropic meds.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>EKG, VBG. Labs: troponin, CBC, NT-proBNP, CMP, lipids, coags, iron studies, HIV, thiamine, TSH, UDS.</li><li>Imaging: CXR, echocardiogram. Monitor telemetry/CCU for advanced therapies.</li></ul><h3 class="g-h">Management</h3><ul class="g-list"><li><strong>ACE-i:</strong> if ≤40%; switch to ARNi (sacubitril/valsartan) in NYHA II/III — start 36 h after last ACE-i dose.</li><li><strong>Beta-blocker:</strong> carvedilol, metoprolol succinate, bisoprolol (mortality benefit).</li><li><strong>Diuretics:</strong> bumetanide/furosemide/torsemide; metolazone or acetazolamide for refractory edema.</li><li><strong>SGLT2:</strong> empagliflozin 10 mg daily (HFrEF, NYHA II–IV), even if not diabetic.</li><li><strong>MRA:</strong> HFrEF <35%, NYHA II–IV — spironolactone/eplerenone 25 mg (eGFR >30, K <5).</li><li><strong>Statin:</strong> if prior ACS/MI.</li><li><strong>Hydralazine + isosorbide dinitrate:</strong> select patients, NYHA III–IV.</li><li><strong>ICD:</strong> 40 days post-MI, LVEF ≤30%, NYHA I; or NYHA I–III with LVEF ≤35%. CRT-D if NYHA II–IV, LVEF ≤35%, NSR with QRS ≥150 ms LBBB.</li><li>General: start low; target SBP <120; Na 2–3 g/day; cardiac rehab; ivabradine if NYHA II/III, ≤40%, max BB, HR ≥70.</li></ul><h3 class="g-h">Avoid</h3><ul class="g-list"><li>Non-dihydropyridine CCBs (e.g., diltiazem) if ≤50%.</li><li>Class IC antiarrhythmics, thiazolidinediones, DPP-4 inhibitors (saxa-, ala-).</li></ul>`
    },
    {
      id: 'af', type: 'ref',
      title: "Atrial Fibrillation",
      subtitle: "Rate / rhythm / anticoagulation",
      keywords: "af atrial fibrillation rate rhythm cardioversion chadsvasc digoxin diltiazem",
      body: `<h3 class="g-h">Red flags</h3><ul class="g-list"><li>Symptomatic AF (SOB, chest pain, HF). If hemodynamically unstable: ACLS and urgent cardioversion.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>EKG, VBG. Labs: troponin (if ischemia), CBC, BNP, BUN, CMP, glucose, TSH, UDS.</li><li>Imaging: CXR, echocardiogram. Monitor telemetry / step-down ICCU.</li><li>Determine clear precipitant and whether onset <48 h.</li><li>Cardiac causes: CAD, HF, HTN, pericarditis, surgery. Non-cardiac: electrolytes, sepsis, thyrotoxicosis, PE, drugs/alcohol.</li></ul><h3 class="g-h">Rate control (goal 60–100 bpm)</h3><ul class="g-list"><li><strong>Beta-blocker:</strong> metoprolol 2–5 mg IV over 3–5 min, repeat q5 min up to 15 mg; then 5 mg q4–6 h or 12.5–25 mg PO q6–12 h. Avoid if bronchospasm or new HF.</li><li><strong>CCB:</strong> diltiazem 0.25 mg/kg IV bolus (max 20 mg); 2nd bolus 0.35 mg/kg (max 25 mg); infusion 5→15 mg/h. Avoid in HF.</li><li><strong>Digoxin:</strong> preferred in HF/hypotension. Load 10 mcg/kg in 3 divided doses q8 h; maintenance 125–250 mcg daily (62.5 mcg elderly); target level 0.6–0.9 ng/mL.</li></ul><h3 class="g-h">Rhythm control (onset <48 h)</h3><ul class="g-list"><li>Synchronized DC cardioversion.</li><li><strong>IV amiodarone:</strong> 150 mg over 10 min, then 1 mg/min ×6 h, then 0.5 mg/min ×18 h (total load up to 10 g). Oral: 400 mg q8 h.</li><li>If pre-excitation suspected: call cardiology attending.</li><li><strong>Magnesium sulfate:</strong> 2.5 g over 20 min, then 2.5 g over 2 h.</li></ul><h3 class="g-h">Anticoagulation</h3><ul class="g-list"><li>If ≥24 h: calculate CHA₂DS₂-VASc and HAS-BLED. Chronic OAC preferred over VKA; enoxaparin 1 mg/kg BID acutely.</li></ul>`
    },
    {
      id: 'htn-emerg', type: 'ref',
      title: "Hypertensive Emergencies",
      subtitle: "Urgency vs emergency",
      keywords: "hypertension htn emergency urgency labetalol nicardipine end organ",
      body: `<h3 class="g-h">Define</h3><ul class="g-list"><li><strong>Urgency:</strong> ≥180/120 asymptomatic, no end-organ damage (headache common).</li><li><strong>Emergency:</strong> signs of end-organ damage — neuro (seizure, focal deficit), N/V (↑ICP), chest pain (ACS), back pain (dissection), dyspnea (HF).</li></ul><h3 class="g-h">Assessment</h3><ul class="g-list"><li>Check cuff size. Labs: VBG, CBC, blood film, CMP, coags, troponin, BNP.</li><li>EKG (LVH, ischemia), CXR, urinalysis + ACR, fundoscopy, CT/MR brain, echo.</li><li>Screen for secondary HTN only if <30 or resistant (≥3 agents).</li></ul><h3 class="g-h">Urgency management</h3><ul class="g-list"><li>Target ~160/110; do not lower >25–30% over first 2–4 h.</li><li>Oral clonidine 0.1 mg (avoid in ischemic CM/HFrEF) or captopril 6.25 mg.</li><li>IV hydralazine 10–20 mg q4–6 h (reflex tachycardia; avoid in HF).</li><li>If sustained asymptomatic: amlodipine 5–10 mg/day over 1–2 days.</li></ul><h3 class="g-h">Emergency management</h3><ul class="g-list"><li>Target: first hour <180/<120, then <160/<110 over next 23 h.</li><li><strong>Labetalol:</strong> 10–20 mg IV over 1–2 min, repeat ×1; infusion 0.5–2 mg/min. Avoid in obstructive lung disease, HF, 2nd/3rd-degree block.</li><li><strong>Nicardipine:</strong> 5 mg/h IV, titrate 2.5 mg/h q5–15 min, max 15 mg/h.</li><li><strong>Nitroglycerin</strong> (acute HF): 5→100 mcg/min. Avoid in severe AS, MS, HOCM, cerebral hemorrhage.</li></ul><h3 class="g-h">Special cases</h3><ul class="g-list"><li>Ischemic stroke: don't lower unless ≥185/110 (for reperfusion) or ≥220/120.</li><li>Aortic dissection: rapidly lower to SBP 100–120 with labetalol.</li><li>Acute HF: add loop diuretic; avoid hydralazine and labetalol.</li></ul>`
    },
    {
      id: 'hyperk', type: 'ref',
      title: "Hyperkalemia",
      subtitle: "Severity & stabilization",
      keywords: "hyperkalemia potassium calcium gluconate insulin kayexalate lokelma",
      body: `<h3 class="g-h">Severity</h3><ul class="g-list"><li>Mild 5.5–5.9; moderate 6.0–6.4; severe >6.4 mEq/L.</li><li>Symptoms (≥7.0): fatigue, weakness, paralysis, paresthesia, palpitations, conduction abnormalities.</li></ul><h3 class="g-h">Initial steps</h3><ul class="g-list"><li>Labs: VBG (urgent K⁺, pH), CBC, CMP, glucose. Telemetry; step-down/ICU if severe.</li><li>EKG: peaked T waves, short QT, PR/QRS prolongation, sine wave. Low-potassium diet.</li></ul><h3 class="g-h">Cardiac stabilization</h3><ul class="g-list"><li><strong>Calcium gluconate:</strong> 5–10 mL of 10% over 2–3 min if EKG changes; repeat after 5 min if persistent. If digoxin toxicity: dilute in 100 mL D5 over 20–30 min.</li></ul><h3 class="g-h">Shift potassium</h3><ul class="g-list"><li><strong>Insulin/glucose:</strong> 10 units in 50 mL D50 over 15 min (or 10–20 units in D10). Monitor glucose hourly ×5–6 h.</li><li><strong>Beta-agonist:</strong> nebulized albuterol 10–20 mg over 10 min (avoid if tachycardia/ischemia).</li><li><strong>Sodium bicarbonate:</strong> 150 mEq in 1 L D5 over 2–4 h.</li><li><strong>Loop diuretic:</strong> 40–80 mg if fluid overloaded.</li></ul><h3 class="g-h">Remove potassium</h3><ul class="g-list"><li>Kayexalate 15 g 1–4×/day (risk: bowel necrosis), or lokelma 10 g TID (≤48 h; max 15 g/day maintenance).</li><li>Dialysis if severe renal dysfunction or refractory. Consult nephrology; stop nephrotoxins.</li></ul>`
    },
    {
      id: 'hyperca', type: 'ref',
      title: "Hypercalcemia",
      subtitle: "Severity & treatment",
      keywords: "hypercalcemia calcium pth bisphosphonate calcitonin zoledronic",
      body: `<h3 class="g-h">Severity</h3><ul class="g-list"><li>Mild 10.5–12; moderate 12.1–14; severe >14 mg/dL.</li><li>Symptoms: bones, stones, groans, psychic moans — bone/abdominal pain, constipation, nausea, HTN, weakness, confusion, obtundation.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Labs: VBG (ionized Ca), CBC, CMP, PTH, vitamin D, magnesium, SPEP/UPEP, TFTs.</li><li>EKG: short QTc, widened T wave. Transfer to step-down/ICU if severe.</li></ul><h3 class="g-h">Severe management</h3><ul class="g-list"><li><strong>IV hydration:</strong> isotonic saline 200–300 mL/h (urine output 100–150 mL/h); loop diuretic only if renal/cardiac failure.</li><li><strong>Zoledronic acid</strong> 4 mg over 15 min or pamidronate 60–90 mg over 2 h (onset 2–4 days).</li><li><strong>Calcitonin</strong> 4 IU/kg (onset 4–6 h; first 48 h only — tachyphylaxis).</li><li><strong>Denosumab</strong> 60 mg SQ if refractory (nephrology approval).</li><li>Dialysis if 18–20 mg/dL with neuro symptoms or renal failure.</li></ul><h3 class="g-h">Other</h3><ul class="g-list"><li>Mild: avoid precipitants, prolonged bed rest, high-calcium diet; encourage oral intake.</li><li>Moderate: saline ± bisphosphonate.</li><li>Prednisone 20–40 mg/day for sarcoid/lymphoma; cinacalcet for parathyroid cancer/secondary hyperparathyroidism.</li></ul>`
    },
    {
      id: 'aki', type: 'ref',
      title: "Acute Kidney Injury",
      subtitle: "Staging & management",
      keywords: "aki acute kidney injury creatinine atn prerenal dialysis nephrology",
      body: `<h3 class="g-h">Staging (KDIGO)</h3><ul class="g-list"><li>Stage 1: 1.5–1.9× baseline or ↑≥0.3; UO <0.5 mL/kg/h ×6–12 h.</li><li>Stage 2: 2.0–2.9× baseline; UO <0.5 mL/kg/h ≥12 h.</li><li>Stage 3: 3.0× baseline or ≥4 mg/dL; UO <0.3 mL/kg/h ≥24 h or anuria ≥12 h.</li></ul><h3 class="g-h">Causes</h3><ul class="g-list"><li>Sepsis/hypoperfusion, toxins (drugs, contrast), obstruction, parenchymal disease.</li><li>Offenders: ACE-i/ARB, NSAIDs, aminoglycosides, amphotericin, tenofovir, contrast.</li><li>Distribution: ATN 45%, prerenal 21%, acute-on-chronic 13%, obstruction 10%, GN/vasculitis 4%, AIN 2%, atheroemboli 1%.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Signs: drug rash (AIN), blue toes (cholesterol emboli), HF (cardiorenal), ascites/jaundice (hepatorenal).</li><li>Urinalysis: blood+protein → GN; proteinuria → ACR; septic → MSU.</li><li>Labs: CBC, CMP, HbA1c, VBG; renal screen (ANCA, anti-GBM, dsDNA, ANA/ENA, C3/C4, HIV, Hep B/C), CK, SPEP/UPEP.</li><li>Imaging: EKG, CXR, renal US (obstruction → urology), CT if stones; PVRs; biopsy with nephrology.</li></ul><h3 class="g-h">Management</h3><ul class="g-list"><li>Remove offending agent; refer nephrology early (24–48 h).</li><li>Volume expansion if prerenal — MAP >65; crystalloid 1–3 L then 75 cc/h. Avoid if anuric.</li><li>Pulmonary edema: furosemide 80–200 mg IV (± chlorothiazide); fluid restrict 1–1.5 L/day.</li><li>Acidosis: bicarbonate (target 20–22 mEq/L) cautiously.</li></ul><h3 class="g-h">RRT indications</h3><ul class="g-list"><li>Refractory pulmonary edema; refractory K⁺ >6.5; acidosis pH <7.1; uremia (pericarditis, AMS, seizure); severe poisoning/overdose.</li></ul>`
    },
    {
      id: 'pe', type: 'ref',
      title: "Acute Pulmonary Embolism",
      subtitle: "Risk stratification & anticoagulation",
      keywords: "pe pulmonary embolism wells pesi anticoagulation tpa thrombolysis doac",
      body: `<h3 class="g-h">Diagnosis</h3><ul class="g-list"><li>Sudden dyspnea, pleuritic chest pain, tachycardia, cough, DVT symptoms.</li><li>Wells' score (<2 low, PE rate 1.5%); sPESI ≥1 = high risk (use MDCalc).</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Labs: VBG, CBC, CMP, coags, D-dimer (>500), troponin/BNP if sPESI ≥1.</li><li>Pulse ox, EKG. Imaging: CXR, CTPA, V/Q (if contrast/radiation CI), echo for RV strain.</li></ul><h3 class="g-h">Initial management</h3><ul class="g-list"><li>Oxygen, maintain sats >90%. Telemetry if sPESI ≥1.</li><li>If hypotensive: 500–1000 mL bolus then pressors. Analgesia.</li></ul><h3 class="g-h">Anticoagulation by risk</h3><ul class="g-list"><li><strong>Low risk:</strong> LMWH 1 mg/kg BID or 1.5 mg/kg daily; DOAC (rivaroxaban/apixaban); UFH if CrCl <30.</li><li><strong>Intermediate (submassive, RV dysfunction + ↑trop/BNP):</strong> LMWH or UFH; CDT/mechanical; thrombolysis if persistent hypotension.</li><li><strong>Massive/high-risk (SBP <90 or drop ≥40 mmHg >15 min):</strong> tPA 100 mg/2 h (or 20 mg bolus + 80 mg/2 h), then UFH ≥24 h, then OAC. Embolectomy if thrombolysis CI.</li></ul><h3 class="g-h">DOAC dosing</h3><ul class="g-list"><li>Apixaban 10 mg BID ×7 days; rivaroxaban 15 mg BID ×3 weeks; edoxaban 60 mg daily (30 if <60 kg, needs 5–10 d parenteral); dabigatran 150 mg BID (needs parenteral lead-in).</li><li>IVC filter if anticoagulation CI or recurrence despite it.</li></ul><h3 class="g-h">Special</h3><ul class="g-list"><li>Pregnancy: omit D-dimer; bilateral leg doppler → V/Q or CTPA.</li><li>Malignancy: LMWH preferred. HIT: argatroban/bivalirudin/fondaparinux.</li><li>Discharge: anticoagulate >3 months; consider thrombophilia testing.</li></ul>`
    },
    {
      id: 'copd', type: 'ref',
      title: "COPD Exacerbation",
      subtitle: "Mild\u2013moderate vs severe",
      keywords: "copd exacerbation albuterol ipratropium prednisone niv bipap",
      body: `<h3 class="g-h">Diagnosis</h3><ul class="g-list"><li>Three cardinal symptoms: ↑dyspnea, ↑cough frequency/severity, ↑sputum volume/purulence.</li><li>Assess vitals, oxygenation, IV access.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Labs: VBG (ABG if SpO₂ <88%), CBC, BMP, BNP, D-dimer, troponin, glucose. Procalcitonin/CRP not required.</li><li>Sputum G&S, influenza/RSV panel, EKG, CXR (exclude pneumonia, pneumothorax, edema, effusion).</li></ul><h3 class="g-h">Mild–moderate</h3><ul class="g-list"><li>Target SpO₂ 88–92% if hypercapnia risk; consider step-down.</li><li>Nebulized albuterol 2.5 mg q4–6 h PRN; ipratropium 500 mcg q6–8 h.</li><li>Prednisone 40 mg/day ×5–14 days. Antibiotics/antivirals per guidelines (not for mild). Thromboprophylaxis.</li></ul><h3 class="g-h">Severe</h3><ul class="g-list"><li>If respiratory failure or hypoxemia (<60 mmHg / <90%): consult ICU ± anesthesia.</li><li>Albuterol 2.5 mg q1 h ×2–3 then q2–4 h; ipratropium 500 mcg similarly.</li><li>Methylprednisolone 60 mg IV (1–4×/day per pulmonology) + antibiotics if indicated.</li><li>NIV if pH ≤7.25 (may start <7.35): IPAP 8→15, EPAP 3, backup 16–20, I:E 1:2. Intubate if poor NIV response.</li></ul><h3 class="g-h">Red flags</h3><ul class="g-list"><li>Impending failure: cyanosis, hemodynamic instability, depressed mental status, pH ≤7.25, FiO₂ ≥40% to maintain 88%.</li><li>Differentials: HF, arrhythmia (AF trigger), pneumonia, pneumothorax, PE.</li></ul>`
    },
    {
      id: 'asthma', type: 'ref',
      title: "Asthma Exacerbation",
      subtitle: "Mild\u2013moderate vs severe",
      keywords: "asthma exacerbation albuterol peak flow magnesium prednisone",
      body: `<h3 class="g-h">Diagnosis</h3><ul class="g-list"><li>Recurrent wheeze, cough, chest tightness, breathlessness. Vitals + IV access.</li><li>Labs: VBG (ABG if SpO₂ <90%), CBC, BMP, BNP, D-dimer. Peak flow. CXR (hyperinflation; exclude pneumothorax/pneumonia).</li></ul><h3 class="g-h">Severity</h3><ul class="g-list"><li>Mild–moderate: phrases/sentences, RR 16–30, HR 100–120, SpO₂ >90%, PEF >50%.</li><li>Severe: single words, accessory muscles, hunched, RR >30, SpO₂ <90%, HR >120, PEF ≤50%.</li><li>Impending failure: cyanosis, depressed mental status, can't maintain effort, SpO₂ <90%, PaCO₂ >40.</li></ul><h3 class="g-h">Mild–moderate</h3><ul class="g-list"><li>Admit step-down. Albuterol 2.5–5 mg q20 min ×3 then q1–4 h PRN.</li><li>Ipratropium 500 mcg q20 min ×3 then stop SAMA. Prednisone 40–60 mg/day ×5 days.</li></ul><h3 class="g-h">Severe</h3><ul class="g-list"><li>Target SpO₂ ≥92% (titrate 93–95%); ICU ± anesthesia if respiratory failure.</li><li>Continuous albuterol 10–15 mg over 1 h; add ipratropium 500 mcg q20 min ×3.</li><li>Methylprednisolone 40–60 mg IV. Magnesium 2 g over 20 min.</li><li>Alternatives: epinephrine 0.3–0.5 mg SC or terbutaline 0.25 mg SC (not both); heliox 60–80%. Ventilate/NIV trial if no response.</li></ul><h3 class="g-h">Response</h3><ul class="g-list"><li>Most respond in 24–48 h. Good: PEF >80% (consider discharge). Incomplete: PEF 60–80% — observe 1–3 h.</li><li>Other diagnoses: pneumonia, pneumothorax, bronchiectasis, anaphylaxis (epi 0.3–0.5 mg IM), mucus plugging.</li></ul>`
    },
    {
      id: 'ugib', type: 'ref',
      title: "Upper GI Bleed",
      subtitle: "Variceal vs non-variceal",
      keywords: "ugib upper gi bleed ppi octreotide variceal endoscopy transfusion blatchford",
      body: `<h3 class="g-h">Diagnosis</h3><ul class="g-list"><li>Blood loss above ligament of Treitz: hematemesis, melena, hematochezia (brisk bleeds).</li><li>Variceal (liver disease/known varices) vs non-variceal (PUD, Mallory-Weiss, cancer, esophagitis/gastritis, vascular).</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Vitals (tachycardia, orthostasis = >15% volume loss). Labs: VBG (immediate Hb), CBC, CMP, coags, T&S.</li><li>EKG before octreotide. Risk-stratify with Glasgow-Blatchford (MDCalc).</li></ul><h3 class="g-h">Initial management</h3><ul class="g-list"><li>2 large-bore IVs; step-down/ICU if unstable. Assess airway (aspiration risk), make NPO.</li><li>Fluid resuscitation; transfuse to Hb >7 (>8 if CAD). Consider anticoagulation reversal.</li><li>Endoscopy within 24 h.</li></ul><h3 class="g-h">Medications</h3><ul class="g-list"><li><strong>PPI:</strong> pantoprazole 80 mg IV bolus then 8 mg/h ×72 h, or 40 mg BID.</li><li><strong>Octreotide</strong> (variceal): 50 mcg bolus then 50 mcg/h ×2–5 days (monitor bradycardia).</li><li><strong>Prokinetic:</strong> erythromycin 250 mg over 20–30 min (avoid if long QTc) or metoclopramide 10 mg IV.</li></ul><h3 class="g-h">Transfusion goals</h3><ul class="g-list"><li>Hb >7 (>8 if CAD); platelets if bleeding + <50k; FFP if INR >2 (1 unit per 4 PRBC); PCC if INR >2 (preferred variceal/CHF); vitamin K 1–5 mg if on VKA.</li></ul><h3 class="g-h">Variceal-specific</h3><ul class="g-list"><li>SBP prophylaxis: ceftriaxone 1 g daily ×7 days. Add propranolol 20 mg TID (day 5). TIPS if recurrent.</li><li>Endoscopy findings guide PPI route; capsule/colonoscopy if no cause. Surgery/IR angiography if persistent.</li></ul>`
    },
    {
      id: 'neutfever', type: 'ref',
      title: "Neutropenic Fever",
      subtitle: "Empiric workup & antibiotics",
      keywords: "neutropenic fever cefepime piptazo vancomycin caspofungin anc oncology",
      body: `<h3 class="g-h">Define</h3><ul class="g-list"><li>Temp >101 (or 100.4 for 1 h) with neutropenia (ANC <1500; severe <500).</li><li>Consider if chemo within 6 weeks, bone marrow failure, or immunosuppression.</li></ul><h3 class="g-h">Workup</h3><ul class="g-list"><li>Examine for focus (catheter, soft tissues); SIRS criteria for severity.</li><li>Labs: CBC + differential, CMP, lactate.</li><li>Micro: blood ×2, urine, throat/sputum/stool cultures, CSF if meningitis; fungal markers (galactomannan, beta-D-glucan) — consult ID. Bacteremia documented in only 20–30%.</li><li>Imaging: CXR; CT chest if high-risk.</li></ul><h3 class="g-h">Treatment</h3><ul class="g-list"><li>Start antibiotics within 60 min (after cultures):</li><li><strong>Cefepime</strong> 2 g IV q8 h or <strong>piperacillin-tazobactam</strong> 4.5 g IV q6 h.</li><li>Penicillin allergy: aztreonam 1 g IV q8 h + vancomycin (if catheter/skin/pneumonia/instability) or ciprofloxacin 750 mg BID + clindamycin.</li><li><strong>Caspofungin</strong> 70 mg day 1 then 50 mg daily (add after 4–7 days in high-risk, expected neutropenia >7 days).</li><li>Side-room, IV fluids; continue antibiotics per cultures (7–14 days or until ANC >500).</li></ul><h3 class="g-h">Monitoring</h3><ul class="g-list"><li>Repeat 2 sets blood cultures daily ×first 48 h.</li><li>Persistent fever (>5 days heme/HSCT, >2 days solid tumor): CT sinuses + chest/abdo/pelvis, fungal markers.</li><li>Stop antibiotics if ANC >500 ×2 days, no positive culture, afebrile >48 h.</li><li>G-CSF not routine; per heme-onc guidance.</li></ul>`
    }
  ]
});
